broadcast_results: true
no_explosions: true
no_building: true
no_creatures: true
no_burning: true
autosave: true
wand_item: air
tick_interval: 1
auto_teleport_on_join: true
timeout_forfeit: 60 sec
no_pvp: true
teleporting: true
pager:
    lines: 0
stake:
    max: -1.0
    default: 0.0
    largeIncrement: 10.0
    smallIncrement: 1.0
highlight_last_move: true
auto_delete:
    finished: 15 sec
    not_started: 1 min 30 sec
    running: 28 days
open_invite_cooldown: 3 mins
no_monster_damage: true
no_misc_damage: true
no_monster_attacks: true
ai:
    max_ai_games: 3
    min_move_wait: 1
    name_format: '[AI]<NAME>'
    use_opening_book: true
    lose_on_fail: false
locale: default
ladder:
    initial_position: 1000
league:
    win_points: 2
    draw_points: 1
    loss_points: 0
autostart: true
time_control:
    default: none
    warn_seconds: 30
designer:
    auto_load: true
effects:
    piece_captured: explosion
    piece_selected: sound,name=note_sticks
    piece_unselected: sound,name=note_bass
    piece_moved: sound,name=item_pickup
    check: sound,name=orb_pickup
    game_lost: sound,name=enderman_death
    game_won: sound,name=level_up
    teleport_out: effect,name=smoke,data=4
    teleport_in: effect,name=ender_signal
    piece_riding: true
    volume: 1.0
log_level: INFO
mcstats: true
flying:
    allowed: true
    captive: true
    auto: false
    upper_limit: 50
    outer_limit: 25
    fly_speed: 0.2
    walk_speed: 0.2
database:
    driver: sqlite
    host: localhost
    user: chesscraft
    password: chesscraft
    port: 3306
    name: chesscraft
results:
    pgn_db: true
# 0.3.3 is the last version released which didn't put a version number in the config
version: 0.3.3
